@startuml
title "Restaurant Client Use Case"
' Creates the actors
actor Client
' Creates the diagram elements
(Restaurant) as Rest
(Tables) as Table
(Cuisine) as Kitchen
(Caisse) as Checkout
(Depot) as Deposit
' Creates the notes
note right of Table : Serveur
note left of Checkout : Argent
' Creates the relations
Client -> Rest : Entree
' Creates the hierarchy
Table <|-- Rest
Checkout <|-- Rest
Kitchen <|-- Table : Requete
Kitchen <|-- Deposit : Resource
@enduml
