@startuml
title "Remove Friend"
'actors
actor Username
actor "Profile Owner" as User

User <|-- Username

'use cases
rectangle "Friend Array" {
  usecase UC3
}
usecase "Remove From Friends" as UCUseTheApplication << Main >>
usecase UC1 as "First select the friend array of both the username
and the profile owner and explode them both.
--
Get the username and user (profile owner) out
==
Create Query for them both:
..Conclusion..
Delete both recursively."

' uses
LoggedInUser -> UCUseTheApplication
Username -> UC3
User .up.> UC1
User --> UCUseTheApplication : Receives a deletion notification
@enduml
