@startuml
title "Use Case Title"
'actors
actor User
actor Admin
actor "Another Actor" as AnotherActor

User <|-- Admin

'use cases
rectangle "A Rectangle" {
  usecase UC3
}
usecase "Use the application" as UCUseTheApplication << Main >>
usecase UC1 as "You can use
several lines to define your usecase.
You can also use separators.
--
Several separators are possible.
==
And you can add titles:
..Conclusion..
This allows large description."

' uses
AnotherActor -> UCUseTheApplication
AnotherActor -> UC3
User .up.> UC1
User --> UCUseTheApplication : A small label

@enduml
